version: '3.9'

services:

  bot:
    build:
      context: ./src/Bot.Api
      dockerfile: Dockerfile
    depends_on:
      - mongodb
    container_name: bot
    ports:
      - "5081:8080"

  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - 27017:27017
    volumes:
      - mongodb-data:/data/db

volumes:
  mongodb-data: