version: '3.9'

services:

  bot:
    build:
      context: ./
      dockerfile: Dockerfile
    depends_on:
      - mongodb
    container_name: bot
    environment:
    - BotUserName=${BotUserName}
    - BotApiToken=${BotApiToken}

  mongodb:
    image: mongo:latest
    container_name: mongodb
    volumes:
      - mongodb-data:/data/db

volumes:
  mongodb-data: