//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bot.Api.Resources {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SharedResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SharedResource() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Bot.Api.Resources.SharedResource", typeof(SharedResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на О компании.
        /// </summary>
        public static string AboutCompanyButton {
            get {
                return ResourceManager.GetString("AboutCompanyButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Группа компаний «РусКон» - это динамично развивающееся объединение, занимающее лидирующие позиции на рынке производства и оптовых поставок технической и ....
        /// </summary>
        public static string AboutCompanyText {
            get {
                return ResourceManager.GetString("AboutCompanyText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Супер! Твоё резюме принято!
        ///Сразу же напишем тебе, как найдём подходящую вакансию.
        /// </summary>
        public static string AcceptedResumeMessage {
            get {
                return ResourceManager.GetString("AcceptedResumeMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Панель администратора.
        /// </summary>
        public static string AdminPanelButton {
            get {
                return ResourceManager.GetString("AdminPanelButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Панель администратора
        ///
        ///Здесь вы можете обновить информацию о вакансиях. Для этого отправьте мне Excel-файл с вакансиями.
        /// </summary>
        public static string AdminPanelText {
            get {
                return ResourceManager.GetString("AdminPanelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Откликнуться на заявку.
        /// </summary>
        public static string ApplyVacancyButton {
            get {
                return ResourceManager.GetString("ApplyVacancyButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Назад.
        /// </summary>
        public static string BackButton {
            get {
                return ResourceManager.GetString("BackButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вернуться в стартовое меню.
        /// </summary>
        public static string BackToMainMenuButton {
            get {
                return ResourceManager.GetString("BackToMainMenuButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Звонок.
        /// </summary>
        public static string CallButton {
            get {
                return ResourceManager.GetString("CallButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Окей, значит ты ищешь работу, давай я покажу тебе наши актуальные вакансии.
        ///Подскажи, в каком городе ты ищешь работу, или может, ты хочешь работать онлайн?.
        /// </summary>
        public static string CitiesStartMessage {
            get {
                return ResourceManager.GetString("CitiesStartMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Видео о компании.
        /// </summary>
        public static string CompanyVideoButton {
            get {
                return ResourceManager.GetString("CompanyVideoButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Сайт.
        /// </summary>
        public static string CompanyWebsiteButton {
            get {
                return ResourceManager.GetString("CompanyWebsiteButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Связь с отделом кадров.
        /// </summary>
        public static string ContactWithHRButton {
            get {
                return ResourceManager.GetString("ContactWithHRButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Отлично, теперь выбери направление, которое тебе нравится или посмотри все вакансии по выбранным параметрам.
        /// </summary>
        public static string DirectionStartMessage {
            get {
                return ResourceManager.GetString("DirectionStartMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ошибка загрузки вакансий.
        /// </summary>
        public static string ErrorDocumentUploading {
            get {
                return ResourceManager.GetString("ErrorDocumentUploading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Чат.
        /// </summary>
        public static string HRChatButton {
            get {
                return ResourceManager.GetString("HRChatButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ты можешь связаться с нашим отделом кадров, позвонив по номеру телефона или написав в чат в Телеграм.
        /// </summary>
        public static string HRContactsText {
            get {
                return ResourceManager.GetString("HRContactsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Неверное расширение файла. Должен быть xlsx или xls.
        /// </summary>
        public static string InvalidDocumentExtentions {
            get {
                return ResourceManager.GetString("InvalidDocumentExtentions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Хорошо, разобрались с городом и форматом работы, теперь подскажи, где ты хочешь работать?.
        /// </summary>
        public static string JobTypeStartMessage {
            get {
                return ResourceManager.GetString("JobTypeStartMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Оставить резюме.
        /// </summary>
        public static string LeaveResumeButton {
            get {
                return ResourceManager.GetString("LeaveResumeButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Привет, я бот для поиска работы в группе компаний «РусКон», я могу рассказать тебе о компании и её направлениях, показать актуальные вакансии и помочь связаться с нашим отделом кадров.
        ///
        ///Помоги мне понять, что ты хочешь, нажав на кнопку ниже.
        /// </summary>
        public static string MainMenuGreetings {
            get {
                return ResourceManager.GetString("MainMenuGreetings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на {0} оставил(а) заявку на вакансию:
        ///{1}.
        /// </summary>
        public static string NewRequestText {
            get {
                return ResourceManager.GetString("NewRequestText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на {0} оставил(а) своё резюме.
        /// </summary>
        public static string NewResumeText {
            get {
                return ResourceManager.GetString("NewResumeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Нет подходящей вакансии.
        /// </summary>
        public static string NoSuitableVacancyButton {
            get {
                return ResourceManager.GetString("NoSuitableVacancyButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Не нашлось подходящей вакансии? Давай я уведомлю тебя, когда появятся вакансии по твоим параметрам?
        ///
        ///Или можешь оставить своё резюме и наш отдел кадров предложит тебе подходящую вакансию!.
        /// </summary>
        public static string NotFoundVacanciesButton {
            get {
                return ResourceManager.GetString("NotFoundVacanciesButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Работа онлайн.
        /// </summary>
        public static string OnlineJobButton {
            get {
                return ResourceManager.GetString("OnlineJobButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Задать вопрос.
        /// </summary>
        public static string QuestionButton {
            get {
                return ResourceManager.GetString("QuestionButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Прикрепи своё резюме или напиши его текстом в чат.
        /// </summary>
        public static string ResumeStartMessage {
            get {
                return ResourceManager.GetString("ResumeStartMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Выбрать город.
        /// </summary>
        public static string ShowCitiesButton {
            get {
                return ResourceManager.GetString("ShowCitiesButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Выбрать направление.
        /// </summary>
        public static string ShowDirectionsButton {
            get {
                return ResourceManager.GetString("ShowDirectionsButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Пропустить этот шаг.
        /// </summary>
        public static string SkipStepButton {
            get {
                return ResourceManager.GetString("SkipStepButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Наши социальные сети.
        /// </summary>
        public static string SocialMediaButton {
            get {
                return ResourceManager.GetString("SocialMediaButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на В наших социальных сетях можно следить за новостями и жизнью компании.
        /// </summary>
        public static string SocialMediaText {
            get {
                return ResourceManager.GetString("SocialMediaText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Подписаться на уведомление.
        /// </summary>
        public static string SubscribeToNotificationButton {
            get {
                return ResourceManager.GetString("SubscribeToNotificationButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Отлично!
        ///Скоро с тобой свяжется специалист и обсудит детали .
        /// </summary>
        public static string SuccessApplyVacancyText {
            get {
                return ResourceManager.GetString("SuccessApplyVacancyText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Загрузка вакансий из файла прошла успешно!.
        /// </summary>
        public static string SuccessDocumentUploading {
            get {
                return ResourceManager.GetString("SuccessDocumentUploading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Отлично, тогда будем на связи.
        /// </summary>
        public static string SuccessSubscribtionToNotification {
            get {
                return ResourceManager.GetString("SuccessSubscribtionToNotification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Канал в Телеграм.
        /// </summary>
        public static string TelegramChannelButton {
            get {
                return ResourceManager.GetString("TelegramChannelButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вакансии.
        /// </summary>
        public static string VacanciesButton {
            get {
                return ResourceManager.GetString("VacanciesButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Посмотреть все вакансии.
        /// </summary>
        public static string ViewAllVacanciesButton {
            get {
                return ResourceManager.GetString("ViewAllVacanciesButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Группа в ВК.
        /// </summary>
        public static string VKGroupButton {
            get {
                return ResourceManager.GetString("VKGroupButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Сожалею, но в этом городе у нас нет вакансий.
        /// </summary>
        public static string WrongCityText {
            get {
                return ResourceManager.GetString("WrongCityText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на У нас нет такого направления.
        /// </summary>
        public static string WrongDirectionText {
            get {
                return ResourceManager.GetString("WrongDirectionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Не найдена вакансия с таким идентификатором.
        /// </summary>
        public static string WrongVacancyId {
            get {
                return ResourceManager.GetString("WrongVacancyId", resourceCulture);
            }
        }
    }
}
