//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bot.Api.Resources {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SharedResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SharedResource() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Bot.Api.Resources.SharedResource", typeof(SharedResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на О компании.
        /// </summary>
        public static string AboutCompanyButton {
            get {
                return ResourceManager.GetString("AboutCompanyButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Группа компаний «РусКон» - это динамично развивающееся объединение, занимающее лидирующие позиции на рынке производства и оптовых поставок технической и ....
        /// </summary>
        public static string AboutCompanyText {
            get {
                return ResourceManager.GetString("AboutCompanyText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Панель администратора.
        /// </summary>
        public static string AdminPanelButton {
            get {
                return ResourceManager.GetString("AdminPanelButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Панель администратора
        ///
        ///Здесь вы можете обновить информацию о вакансиях. Для этого отправьте мне Excel-файл с вакансиями.
        /// </summary>
        public static string AdminPanelText {
            get {
                return ResourceManager.GetString("AdminPanelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вернуться в стартовое меню.
        /// </summary>
        public static string BackToMainMenuButton {
            get {
                return ResourceManager.GetString("BackToMainMenuButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Звонок.
        /// </summary>
        public static string CallButton {
            get {
                return ResourceManager.GetString("CallButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Видео о компании.
        /// </summary>
        public static string CompanyVideoButton {
            get {
                return ResourceManager.GetString("CompanyVideoButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Сайт.
        /// </summary>
        public static string CompanyWebsiteButton {
            get {
                return ResourceManager.GetString("CompanyWebsiteButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Связь с отделом кадров.
        /// </summary>
        public static string ContactWithHRButton {
            get {
                return ResourceManager.GetString("ContactWithHRButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ошибка загрузки вакансий.
        /// </summary>
        public static string ErrorDocumentUploading {
            get {
                return ResourceManager.GetString("ErrorDocumentUploading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Чат.
        /// </summary>
        public static string HRChatButton {
            get {
                return ResourceManager.GetString("HRChatButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ты можешь связаться с нашим отделом кадров, позвонив по номеру телефона или написав в чат в Телеграм.
        /// </summary>
        public static string HRContactsText {
            get {
                return ResourceManager.GetString("HRContactsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Неверное расширение файла. Должен быть xlsx или xls.
        /// </summary>
        public static string InvalidDocumentExtentions {
            get {
                return ResourceManager.GetString("InvalidDocumentExtentions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Привет, я бот для поиска работы в группе компаний «РусКон», я могу рассказать тебе о компании и её направлениях, показать актуальные вакансии и помочь связаться с нашим отделом кадров.
        ///
        ///Помоги мне понять, что ты хочешь, нажав на кнопку ниже.
        /// </summary>
        public static string MainMenuGreetings {
            get {
                return ResourceManager.GetString("MainMenuGreetings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Наши социальные сети.
        /// </summary>
        public static string SocialMediaButton {
            get {
                return ResourceManager.GetString("SocialMediaButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на В наших социальных сетях можно следить за новостями и жизнью компании.
        /// </summary>
        public static string SocialMediaText {
            get {
                return ResourceManager.GetString("SocialMediaText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Загрузка вакансий из файла прошла успешно!.
        /// </summary>
        public static string SuccessDocumentUploading {
            get {
                return ResourceManager.GetString("SuccessDocumentUploading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Канал в Телеграм.
        /// </summary>
        public static string TelegramChannelButton {
            get {
                return ResourceManager.GetString("TelegramChannelButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вакансии.
        /// </summary>
        public static string VacanciesButton {
            get {
                return ResourceManager.GetString("VacanciesButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Группа в ВК.
        /// </summary>
        public static string VKGroupButton {
            get {
                return ResourceManager.GetString("VKGroupButton", resourceCulture);
            }
        }
    }
}
